### ISSUE TITLE
Discuss whether we should use `server-middleware` to keep the server and the client under one repo.

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/Backend#12]
## Discuss whether we should use `server-middleware` to keep the server and the client under one repo.

I discovered this recently, it's really cool...
I can create this file...
![image](https://user-images.githubusercontent.com/72760579/121243396-aaf26400-c86b-11eb-8d1c-6a045968db71.png)
Export an express app...
```js
const app = require('express')()

const bodyParser = require('body-parser')
app.use(bodyParser.json())

app.post('/api/auth/login', (req, res) => {
  console.log(req.body)
  console.log('User was trying to login')
  res.send({ token: 'lol' }) // TODO
})
app.post('/api/auth/users', (req, res) => {
  console.log(req.body)
  console.log('User was trying to be created')
  res.send('done') // TODO
})
app.get('/api/auth/user', (req, res) => {
  console.log(req.body)
  console.log('User was trying to use token')
  res.send({
    user: { username: 'bob' },
  }) // TODO
})

module.exports = app
```

And those API paths will be created. We can also still use monk and other modules in here.
Then you just put
```js
{
  serverMiddleware: ['~/server-middleware/server.js'],
}
```
in your nuxt.config.js and you got yourself a server...

---
### Pros:
- No more variables for backend and frontend urls
- API will not need cors and such
- We can use socket.io to make things live (like reactions)
- No need for 2 domains
- New APIs created will now just need one PR rather than 2 to just things in the back and front ends
- New users will only need to look at one repo to explore the source code.

### Cons:
- Everything will be in one repo, and that might be messy for some people...
- idk...

cc @FunctionalMetatable I want to know what you think, since you have been helping a lot in this project... also check your mail for an org invite :eyes:

**Comment by FunctionalMetatable** [comment]
with nuxtjs's vercel server-builder - everything can be in one repo

**Comment by TheColaber** [comment]
So you like this idea? Great, let's merge your open PR in the backend, and I'll PR in FlagClicked/FlagClicked with everything here. But I need to look into "nuxtjs's vercel server-builder" first.

**Comment by TheColaber** [comment]
But about vercel... I don't want to do all this stuff... https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project, because it seems that vercel is putting so much advertisement on their product from our site.

**Comment by TheColaber** [comment]
Closes #9

**Comment by TheColaber** [comment]
This Repo will probably be deleted when this is resolved.

**Comment by FunctionalMetatable** [comment]
Fosshost then?

**Comment by TheColaber** [comment]
@FunctionalMetatable Maybe you can explain how this example can easily just use that https://github.com/nuxt/vercel-builder/tree/main/examples/basic API folder to do that... does nuxt do that by default?

**Comment by FunctionalMetatable** [comment]
The API folder is a vercel-based thing where there are javascript files in that directory for serverless functions.

**Comment by FunctionalMetatable** [comment]
@Steve0Greatness @markverb1 @CubeyTheCube What do you think?

**Comment by Steve0Greatness** [comment]
@FunctionalMetatable I think it would make it a little easier to navigate them if they are in the same repo.
However, whichever one works better, would be better

**Comment by FunctionalMetatable** [comment]
@TheColaber should I start work on this?

**Comment by TheColaber** [comment]
Of course

**Comment by FunctionalMetatable** [comment]
@TheColaber I've started work on this and the Vuex stores become a bit confusing after i've added the server middleware

**Comment by TheColaber** [comment]
Yeah, I honestly don't completely understand what Vuex stores are and how to use them. If this is about the auth, shouldn't it stay the same for the most part?

**Comment by FunctionalMetatable** [comment]
> Yeah, I honestly don't completely understand what Vuex stores are and how to use them. If this is about the auth, shouldn't it stay the same for the most part?

I have to rewrite the stores to use the same server (we have to use the client header "Host") and the nuxt app is just fetching itself in the store
